### ISSUE TITLE
Fails to download exampletimer.zip

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [Misfiy/RespawnTimer#1]
Yeah it just throws an error,

shouldn't be an issue if you already have the example timer from normal respawn timer or if you download the one from this repo.

**Comment by Misfiy** [comment]
I haven't changed anything except for the support for UIU and SH. So it's still trying to download from the original repo, for now just install it manually. May fix it in the near future. :)

**Comment by theOneTrueFunniBoi** [comment]
Hmmm, it could be that the version text does not match a respawn timer version. Because the version text is used in deciding what exampletimer template to download. So you could hard code it, or redirect it to your GitHub instead of the exiled GitHub.

**Comment by Misfiy** [comment]
Remind me on my Discord server tomorrow, and I will look at it :)

**Comment by Misfiy** [comment]
This has been fixed in [https://github.com/Misfiy/RespawnTimer/releases/tag/4.0.4](this release)
